"""ModelHooks and DataHooks - lifecycle hooks for Model and DataModule."""

from typing import Any, Optional

import paddle


class ModelHooks:
    """Hooks called on the Model during training/validation/test/predict."""

    def on_fit_start(self) -> None: ...
    def on_fit_end(self) -> None: ...

    def on_train_start(self) -> None: ...
    def on_train_end(self) -> None: ...

    def on_train_batch_start(self, batch: Any, batch_idx: int) -> Optional[int]: ...
    def on_train_batch_end(self, outputs: Any, batch: Any, batch_idx: int) -> None: ...
    def on_train_epoch_start(self) -> None: ...
    def on_train_epoch_end(self) -> None: ...

    def on_validation_start(self) -> None: ...
    def on_validation_end(self) -> None: ...
    def on_validation_batch_start(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_validation_batch_end(self, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_validation_epoch_start(self) -> None: ...
    def on_validation_epoch_end(self) -> None: ...

    def on_test_start(self) -> None: ...
    def on_test_end(self) -> None: ...
    def on_test_batch_start(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_test_batch_end(self, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_test_epoch_start(self) -> None: ...
    def on_test_epoch_end(self) -> None: ...

    def on_predict_start(self) -> None: ...
    def on_predict_end(self) -> None: ...
    def on_predict_batch_start(self, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_predict_batch_end(self, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0) -> None: ...
    def on_predict_epoch_start(self) -> None: ...
    def on_predict_epoch_end(self) -> None: ...

    def on_before_backward(self, loss: paddle.Tensor) -> None: ...
    def on_after_backward(self) -> None: ...
    def on_before_optimizer_step(self, optimizer: paddle.optimizer.Optimizer) -> None: ...
    def on_before_zero_grad(self, optimizer: paddle.optimizer.Optimizer) -> None: ...

    def on_validation_model_eval(self) -> None: ...
    def on_validation_model_train(self) -> None: ...
    def on_test_model_eval(self) -> None: ...
    def on_test_model_train(self) -> None: ...

    def configure_model(self) -> None: ...


class DataHooks:
    """Hooks for data lifecycle."""

    def __init__(self) -> None:
        self.prepare_data_per_node: bool = True
        self.allow_zero_length_dataloader_with_multiple_devices: bool = False

    def prepare_data(self) -> None: ...
    def setup(self, stage: str) -> None: ...
    def teardown(self, stage: str) -> None: ...

    def train_dataloader(self) -> Any:
        raise NotImplementedError("train_dataloader must be implemented")

    def val_dataloader(self) -> Any:
        raise NotImplementedError("val_dataloader must be implemented")

    def test_dataloader(self) -> Any:
        raise NotImplementedError("test_dataloader must be implemented")

    def predict_dataloader(self) -> Any:
        raise NotImplementedError("predict_dataloader must be implemented")
