"""Callback base class - all lifecycle hooks with default no-op implementations."""

from typing import Any


class Callback:
    """Base class for all callbacks. All hooks have default no-op implementations."""

    @property
    def state_key(self) -> str:
        """Identifies the callback's state in the checkpoint.

        Two callbacks of the same type but different configuration (e.g. two
        ``EarlyStopping`` on different monitors) must not collide on one key,
        or restoring a checkpoint would load one callback's state into the
        other. Subclasses override this (via :meth:`_generate_state_key`) to
        fold their distinguishing arguments into the key.
        """
        return self.__class__.__qualname__

    def _generate_state_key(self, **kwargs: Any) -> str:
        """Build a state key from the class name plus distinguishing kwargs."""
        return f"{self.__class__.__qualname__}{repr(sorted(kwargs.items()))}"

    def setup(self, trainer: Any, model: Any, stage: str) -> None: ...
    def teardown(self, trainer: Any, model: Any, stage: str) -> None: ...

    def on_fit_start(self, trainer: Any, model: Any) -> None: ...
    def on_fit_end(self, trainer: Any, model: Any) -> None: ...

    def on_train_start(self, trainer: Any, model: Any) -> None: ...
    def on_train_end(self, trainer: Any, model: Any) -> None: ...

    def on_train_batch_start(self, trainer: Any, model: Any, batch: Any, batch_idx: int) -> None: ...
    def on_train_batch_end(self, trainer: Any, model: Any, outputs: Any, batch: Any, batch_idx: int) -> None: ...

    def on_train_epoch_start(self, trainer: Any, model: Any) -> None: ...
    def on_train_epoch_end(self, trainer: Any, model: Any) -> None: ...

    def on_validation_start(self, trainer: Any, model: Any) -> None: ...
    def on_validation_end(self, trainer: Any, model: Any) -> None: ...

    def on_validation_batch_start(
        self, trainer: Any, model: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...
    def on_validation_batch_end(
        self, trainer: Any, model: Any, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...

    def on_validation_epoch_start(self, trainer: Any, model: Any) -> None: ...
    def on_validation_epoch_end(self, trainer: Any, model: Any) -> None: ...

    def on_sanity_check_start(self, trainer: Any, model: Any) -> None: ...
    def on_sanity_check_end(self, trainer: Any, model: Any) -> None: ...

    def on_test_start(self, trainer: Any, model: Any) -> None: ...
    def on_test_end(self, trainer: Any, model: Any) -> None: ...

    def on_test_batch_start(
        self, trainer: Any, model: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...
    def on_test_batch_end(
        self, trainer: Any, model: Any, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...

    def on_test_epoch_start(self, trainer: Any, model: Any) -> None: ...
    def on_test_epoch_end(self, trainer: Any, model: Any) -> None: ...

    def on_predict_start(self, trainer: Any, model: Any) -> None: ...
    def on_predict_end(self, trainer: Any, model: Any) -> None: ...

    def on_predict_epoch_start(self, trainer: Any, model: Any) -> None: ...
    def on_predict_epoch_end(self, trainer: Any, model: Any) -> None: ...

    def on_predict_batch_start(
        self, trainer: Any, model: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...
    def on_predict_batch_end(
        self, trainer: Any, model: Any, outputs: Any, batch: Any, batch_idx: int, dataloader_idx: int = 0
    ) -> None: ...

    def on_exception(self, trainer: Any, model: Any, exception: BaseException) -> None: ...

    def state_dict(self) -> dict[str, Any]:
        return {}

    def load_state_dict(self, state_dict: dict[str, Any]) -> None: ...

    def on_save_checkpoint(self, trainer: Any, model: Any, checkpoint: dict[str, Any]) -> None: ...
    def on_load_checkpoint(self, trainer: Any, model: Any, checkpoint: dict[str, Any]) -> None: ...

    def on_before_backward(self, trainer: Any, model: Any, loss: Any) -> None: ...
    def on_after_backward(self, trainer: Any, model: Any) -> None: ...
    def on_before_optimizer_step(self, trainer: Any, model: Any, optimizer: Any) -> None: ...
